services:
  boveda_sftp:
    image: atmoz/sftp
    container_name: boveda_sftp
    restart: unless-stopped
    networks:
      - public_net
    ports:
      - 1234:22
    volumes:
      - ./users/users.conf:/etc/sftp/users.conf:ro
      - ./certs/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./certs/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - /srv/boveda_data/:/srv/boveda_data

  boveda_webserver:
    image: nginx:latest
    container_name: boveda_webserver
    restart: unless-stopped
    networks:
      - public_net
    expose:
      - 123
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/ssl:ro
      - /srv/boveda_data/:/srv/boveda_data

networks:
  public_net:
    name: net_public