services:
  boveda_sftp:
    image: atmoz/sftp
    container_name: boveda_sftp
    restart: unless-stopped
    networks:
      - boveda_web
    ports:
      - 4287:22
    volumes:
      - ./comp1/conf/users/users.conf:/etc/sftp/users.conf
      - ./comp1/conf/certs/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./comp1/conf/certs/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./comp1/vol/sftp_data/vdeap/upload:/home/vdeap/upload
      - ./comp1/vol/sftp_data/shared:/home/shared

  boveda_webserver:
    image: nginx:latest
    container_name: boveda_webserver
    restart: unless-stopped
    networks:
      - boveda_web
    ports:
      - 4286:80
    volumes:
      - ./comp1/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./comp1/vol/sftp_data/vdeap/upload:/usr/share/nginx/html:ro

networks:
  boveda_web:
    driver: bridge
    name: net_boveda
