services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - ./var/broker/redisdata:/data
    networks:
      paper_net:
    expose:
      - "6379"

  db:
    image: docker.io/library/mariadb:11
    container_name: paperless_db
    restart: unless-stopped
    volumes:
      - ./var/db/dbdata:/var/lib/mysql
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: lacontraescontra
      MARIADB_ROOT_PASSWORD: lacontraaesroot
    networks:
      paper_net:
    expose:
      - "3306"

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless_webserver
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    networks:
      paper_net:
    ports:
      - "4285:8000"
    volumes:
      - ./var/webserver/data:/usr/src/paperless/data
      - ./var/webserver/media:/usr/src/paperless/media
      - ./var/webserver/export:/usr/src/paperless/export
      - ./var/webserver/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: lacontraescontra
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    container_name: paperless_gotenberg
    restart: unless-stopped
    networks:
      paper_net:
    expose:
      - "3000"
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: paperless_tika
    restart: unless-stopped
    networks:
      paper_net:
    expose:
      - "9998"

networks:
  paper_net:
    name: paperless_net
    driver: bridge
