services:
  outline:
    container_name: outline-app
    hostname: outline-app
    image: docker.getoutline.com/outlinewiki/outline:latest
    ports:
      - 10301:${PORT}
    volumes:
      - ./storage-data:/var/lib/outline/data
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      PGSSLMODE: disable
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: postgres://user:pass@outline-postgres:5432/outline
      REDIS_URL: redis://outline-redis:6379
      URL: ${URL}
      PORT: ${PORT}
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
  redis:
    container_name: outline-redis
    hostname: outline-redis
    image: redis
    volumes:
      - ./redis.conf:/redis.conf
    restart: unless-stopped
    command:
      - redis-server
      - /redis.conf
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 30s
      retries: 3
  postgres:
    container_name: outline-postgres
    hostname: outline-postgres
    image: postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -d
        - outline
        - -U
        - user
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
networks: {}

