services:
  ghost:
    image: ghost:latest
    container_name: ghost_webapp
    networks:
      - ghost_net
    restart: unless-stopped
    ports:
      - 4292:2368
    environment:
      url: https://tests.cuspide.club
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASS}
      database__connection__database: ${DB_NAME}
    volumes:
      - ghost_content:/var/lib/ghost/content
    depends_on:
      mariadb:
        condition: service_healthy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ghost_phpmyadmin
    networks:
      - ghost_net
    restart: unless-stopped
    ports:
      - 4293:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:latest
    env_file: ./.env
    container_name: ghost_db
    networks:
      - ghost_net
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - --connect
        - --innodb_initialized
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  ghost_net:
    driver: bridge
    name: ghost_network
volumes:
  ghost_content: null
  mariadb: null

